add more bin utils for simplified service management

diff --git a/bin/start-service b/bin/start-service
--- a/bin/start-service
+++ b/bin/start-service
@@ -4,15 +4,16 @@ IFS=$'\n\t'
 
 #/
 #/ Usage:
-#/              deploy-all
+#/              start-service [service]
 #/ Description:
-#/              deploy entire stack defined by docker-compose.yml;
-#/              if services already exist, they will be updated;
+#/              start an existing service that was previously stopped;
+#/              if service is already started, no action will be taken;
 #/ Commands Used:
-#/              docker swarm init
-#/              docker stack deploy
+#/              docker service ls
+#/              docker service scale
 #/ Examples:
-#/              deploy-all
+#/              start-service plex
+#/              start-service nginx
 #/ Flags:
 #/              --help: display this help message
 #/
@@ -52,16 +53,13 @@ trap cleanup INT TERM EXIT
 # start a new pid
 echo $$ > "${PID_FILE}"
 
-if ! docker node ls | grep -q Active
-then
-	info "initializing swarm ..."
-	docker swarm init
-	info "... done!"
-else
-	info "swarm node is active"
-fi
+[ -n "${1:-}" ] || fatal "service name is required"
 
-info "deploying stack ..."
-docker stack deploy --compose-file "${BIN_DIR}/../docker-compose.yml" mediaserver
+readonly SERVICE_NAME="mediaserver_${1:-}"
+
+docker service ls | grep -q "${SERVICE_NAME}" || fatal "service ${SERVICE_NAME} does not exist"
+
+info "starting service ${SERVICE_NAME} ..."
+docker service scale --detach=true ${SERVICE_NAME}=1
 info "... task is running in background"
 info "check status with 'docker service ls' and 'docker ps'
