update bin scripts

diff --git a/bin/up b/bin/up
--- a/bin/up
+++ b/bin/up
@@ -1,7 +1,19 @@
 #!/usr/bin/env bash
 
+compose_bin="$(which docker-compose | head -n1)" 
+if [ ! -x "$compose_bin" ] 
+then
+	echo "docker-compose not found, please run install script" 1>&2
+	exit 1
+else
+	"$compose_bin" --version
+fi
+
+abs_root() { echo "$(cd "$(dirname "${1}")" && pwd)"; }
+project_root="$(abs_root "$(abs_root "$0")")"
+
 # source environment variables required for containers
-. "$(dirname "$0")"/../compose.env
+. "$project_root/compose.env"
 
 # compose up (recreate if required, no build, remove orphans, disconnected)
-/usr/local/bin/docker-compose -f "$(dirname "$0")"/../docker-compose.yml up -d --no-build --remove-orphans
+"$compose_bin" -f "$project_root/docker-compose.yml" up -d --no-build --remove-orphans
